.TH "libowl.CodeGen" 3 "Thu Nov 27 2014" "libowl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libowl.CodeGen \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCodeGen\fP (List< \fBToken\fP > tokens)"
.br
.ti -1c
.RI "void \fBBuild\fP ()"
.br
.ti -1c
.RI "void \fBBeautify\fP ()"
.br
.ti -1c
.RI "void \fBSerialize\fP (string path, string eolstyle=null)"
.br
.ti -1c
.RI "void \fBSerialize\fP (Stream stream, string eolstyle=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file CodeGen\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libowl from the source code\&.
