.TH "libowl.Token" 3 "Thu Nov 27 2014" "libowl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libowl.Token \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBlibowl\&.TokenAssign\fP, \fBlibowl\&.TokenBracketClosing\fP, \fBlibowl\&.TokenBracketOpening\fP, \fBlibowl\&.TokenComma\fP, \fBlibowl\&.TokenContent\fP, \fBlibowl\&.TokenCurlyClosing\fP, \fBlibowl\&.TokenCurlyOpening\fP, \fBlibowl\&.TokenEOF\fP, \fBlibowl\&.TokenEOL\fP, \fBlibowl\&.TokenEscape\fP, \fBlibowl\&.TokenIdentifier\fP, \fBlibowl\&.TokenParClosing\fP, \fBlibowl\&.TokenParOpening\fP, \fBlibowl\&.TokenSemicolon\fP, \fBlibowl\&.TokenString\fP, and \fBlibowl\&.TokenStyleBlock\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToken\fP (int line)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly int \fBline\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Token\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libowl from the source code\&.
