.TH "libowl.TokenString" 3 "Thu Nov 27 2014" "libowl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libowl.TokenString \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlibowl\&.Token\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTokenString\fP (string str, int line)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file TokenString\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libowl from the source code\&.
