.TH "src/libowl/Verbosity.cs" 3 "Thu Nov 27 2014" "libowl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/libowl/Verbosity.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlibowl\&.Verbosity\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBlibowl\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBlibowl\&.VerbosityLevel\fP { \fBlibowl\&.VerbosityLevel\&.silent\fP, \fBlibowl\&.VerbosityLevel\&.erroronly\fP, \fBlibowl\&.VerbosityLevel\&.warnings\fP, \fBlibowl\&.VerbosityLevel\&.basic\fP, \fBlibowl\&.VerbosityLevel\&.debug\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libowl from the source code\&.
